baseURL = "https://Rufine777.github.io/"
languageCode = "en-US"
title = "Ajul's Portfolio"
theme = "hugo-split-theme"
enableRobotsTXT = true
relativeURLs = false
canonifyURLs = true
disableKinds = ["taxonomy", "RSS"] # keeps site clean
copyright = "© 2025 Ajul T. M"

# Google Analytics (optional — leave empty if not used)
[services]
  [services.googleAnalytics]
    ID = ""

[params]
  author = "Ajul T. M"
  description = "Portfolio site for AI & CSE projects"
  shareImage = "images/pfp.png"
  twitterHandle = "" # add later if needed
  licensed = false
  favicon = "images/pfp.png"

  [params.visual]
    [params.visual.image]
      enable = true
      file = "images/pfp.png"
      position = "center center"
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"

# Navigation Menu (matches your content/*.md files)
[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Projects & Achievements"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 3

[[menu.main]]
  name = "Contact Me"
  url = "/contact/"
  weight = 4

# Security headers (safe defaults for GitHub Pages)
[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Content-Security-Policy = "default-src 'self' https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:;"
      Referrer-Policy = "strict-origin-when-cross-origin"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"

